name: Bug report
description: Found an issue? Report it here
labels: ["bug"]
body:
 - type: markdown
   attributes:
    value: |
     Thanks for taking the time to fill out this bug report for GeyserList! Fill out the following form to your best ability to help us fix the problem.
     Only use this if you're absolutely sure that you found a bug and can reproduce it.
 - type: textarea
   attributes:
    label: Describe the bug
    description: A clear and concise description of what the bug is.
   validations:
    required: true
 - type: input
   attributes:
    label: Page Link
    description: If applicable, please provide a link to the page this bug occurs on.
 - type: textarea
   attributes:
    label: To Reproduce
    description: Steps to reproduce this behaviour
    placeholder: |
     1. Go to '...'
     2. Click on '...'
     3. Scroll down to '...'
     4. See error
   validations:
    required: true
 - type: textarea
   attributes:
    label: Expected behaviour
    description: A clear and concise description of what you expected to happen.
   validations:
    required: true
 - type: textarea
   attributes:
    label: Screenshots / Videos
    description: If applicable, add screenshots to help explain your problem.
 - type: textarea
   attributes:
    label: Client
    description: |
     Please provide us with the client you used when you experienced this issue.
     - Device: [e.g. iPhone 9, Samsung Galaxy S15] <!-- Not necessary if desktop -->
     - OS: [e.g. iOS 6.9, Android 4.20, Windows 95, macOS 13.37]
     - Browser [e.g. stock browser, safari]
     - Version [e.g. 22]
 - type: textarea
   attributes:
    label: Additional Context
    description: Add any other context about the problem here