blank_issues_enabled: false
contact_links:
  - name: Get help on the GeyserMC Discord server
    url: https://discord.gg/geysermc
    about: If you have general questions about the site, please ask them here!
